### PR TITLE
Change hostname setting to use ansible hostname module

### PR DESCRIPTION
**Pull request by Klaas-**
Ansible has a hostname module which should do the trick - no need for shell:
https://docs.ansible.com/ansible/latest/modules/hostname_module.html
I only checked that it works on rhel7.

Also I think that shell task would never fail, you don't set rc=2 anywhere or handle failure of any command

### CODE REVIEW

**Comment by rhmk** [comment]
Klaas, this solution is not working completely. I agree that the hostname module should be used and I am working on it. The ansible_hostname is not necessarily the hostname you want to use. It might another interface, that should be configured for sap access.

**Comment by Klaas-** [comment]
Isn't ansible_hostname the same as $(hostname -s)? If it's not the same you could just run that as command. My main intention was to change to hostname module, not change the behaviour.

**Comment by Klaas-** [comment]
Refs #42 - this is one of the things that needs to happen for check mode :)

**Comment by Klaas-** [comment]
@berndfinger  also opened up two issues about hostname behaviour - #40 and #41 - maybe you can put them all together into one PR and include my proposed change to hostname module. I'll happily abandon this for a better solution.

**Comment by berndfinger** [comment]
@Klaas- Many thanks for your efforts! As you had noticed, I had also fixed this issue. It is now available upstream - see also pull request #46.

**Pull request closed without merging**
