### PR TITLE
solve issues #38, 91, 96...102, 104, 106...111

### PR DESCRIPTION
**Pull request by berndfinger**
- include all bug fixes and features for bz1891638 and bz1891642

### CODE REVIEW

**Review by richm — APPROVED** [review]
lgtm

**Review by richm — APPROVED** [review]
lgtm

**Comment by rhmk** [comment]
I was testing on 8.1 -- looks good

**Review by rhmk — APPROVED** [review]
lgtm

**Review by rhmk — APPROVED** [review]
lgtm

**Pull request merged**
